version: "3"
services:
  cockroachdb:
    image: cockroachdb/cockroach:v2.0.3
    volumes:
      - db-data:/cockroach/cockroach-data
    networks:
      - backend
    ports:
      - 26257:26257
      - 8090:8080
    command: ["start", "--insecure"]
  docker-registry:
    image: registry:2
    volumes:
      - registry-data:/var/lib/registry
      - ./registry-config.yml:/etc/docker/registry/config.yml
    networks:
      - backend
    expose:
      - 5000
    command: ["serve", "/etc/docker/registry/config.yml"]
  app-store:
    image: app-store
    volumes:
      - ./:/go/src/github.com/protosio/app-store
    networks:
      - backend
    entrypoint: go run /go/src/github.com/protosio/app-store/main.go
    command: ["serve"]
    depends_on:
      - cockroachdb
      - docker-registry
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
  # app-store-init:
  #   image: app-store
  #   volumes:
  #     - ./:/go/src/github.com/protosio/app-store
  #   networks:
  #     - backend
  #   entrypoint: go run /go/src/github.com/protosio/app-store/main.go
  #   command: ["init"]
  #   depends_on:
  #     - cockroachdb
  load-balancer:
    image: traefik:alpine
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - backend
    ports:
      - 127.0.0.1:8070:8070
      - 80:80
      - 443:443
    depends_on:
      - app-store

networks:
  backend:

volumes:
  db-data:
  registry-data: