version: "3"
services:
  postgres:
    image: postgres:10.5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${APPSTORE_POSTGRES_PASSWD}
      - POSTGRES_USER=${APPSTORE_POSTGRES_USER}
    networks:
      - backend
  docker-registry:
    image: registry:2
    volumes:
      - registry-data:/var/lib/registry
      - ./registry-config.yml:/etc/docker/registry/config.yml
    networks:
      - backend
    expose:
      - 5000
    command: ["serve", "/etc/docker/registry/config.yml"]
  app-store:
    image: app-store
    volumes:
      - ./:/go/src/github.com/protosio/app-store
    networks:
      - backend
    entrypoint: go run /go/src/github.com/protosio/app-store/main.go --dbhost postgres --dbuser ${APPSTORE_POSTGRES_USER} --dbpass ${APPSTORE_POSTGRES_PASSWD} --dbname ${APPSTORE_POSTGRES_USER}
    command: ["serve"]
    depends_on:
      - postgres
      - docker-registry
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
  load-balancer:
    image: abiosoft/caddy:0.11.0
    environment:
      - CADDYPATH=/etc/caddycerts
      - ACME_AGREE=true
    volumes:
      - ./caddycerts:/etc/caddycerts
      - ./Caddyfile:/etc/Caddyfile
    networks:
      - backend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app-store

networks:
  backend:

volumes:
  db-data:
  registry-data:
