defaultEntryPoints = ["http"]
debug = false
logLevel = "INFO"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  [entryPoints.dashboard]
    address = ":8070"

[api]
entryPoint = "dashboard"
dashboard = true

[file]
  [frontends]
    [frontends.app-store]
      entryPoints = ["http", "https"]
      backend = "backend1"
      [frontends.app-store.routes]
        [frontends.app-store.routes.route0]
          rule = "PathPrefix:/api/"
    [frontends.registry]
      entryPoints = ["http", "https"]
      backend = "backend2"

  [backends]
    [backends.backend1]
      [backends.backend1.servers.server1]
      url = "http://app-store:8000"
    [backends.backend2]
      [backends.backend2.servers.server1]
      url = "http://docker-registry:5000"

[acme]
email = "alex@giurgiu.io"
storage = "/acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
